### ISSUE TITLE
ValueError when running from an empty git repository

### ISSUE THREAD

**Issue by Aratz** [ICB-DCM/pyABC#264] opened 2020-02-12 12:21 UTC
When running pyABC from a directory where a git repository has been initialized but nothing has been committed yet, one gets ```ValueError: Reference at 'refs/heads/master' does not exist``` when setting up the observed data with ```new```.

Steps to reproduce:
1. Create a new directory
2. initialize a new git repository with ```git init```
3. Copy and run any of the examples from the documentation (e.g. ```quickstart.ipynb```)

**Comment by yannikschaelte** [comment] 2020-02-12 12:32
Thanks @Aratz for pointing this out. That is indeed unintended behavior. The reasoning was, I think, to store the commit hash of the working git repo if applicable. We will add a check if the repo has a history already, which should solve the problem.

In the meantime, you should be able to circumvent this by in the repository creating a git history entry, e.g. by ``git add quickstart.ipynb; git commit -m 'initial commit'``. Please let us know if that works for you!

**Comment by Aratz** [comment] 2020-02-12 12:44
Well, the hard was understanding where the issue came from. I understand this bug wouldn't happen in most cases :) Thanks for taking the time to handle this!

**Comment by yannikschaelte** [comment] 2020-02-12 12:53
Tiny fix now on the way in https://github.com/ICB-DCM/pyABC/pull/265, will be part of the next release in a few days.

Let us know if you have questions or encounter further problems ;)

**Closed** 2020-02-20 13:46 UTC
Labels: bug
